// <auto-generated />
namespace CRUD.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_MarkUpPlanToAgnet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_MarkUpPlanToAgnet));
        
        string IMigrationMetadata.Id
        {
            get { return "201907151006289_Add_MarkUpPlanToAgnet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
